### ISSUE TITLE
Invalid class paths

### ISSUE THREAD

**Issue by SOF3** [thebigsmileXD/customui#1]
While `antigen` is specified, the source files should be placed inside a `src` folder relative to `virion.yml` (not `viron.yml`), still in PSR-0 structure. There are plans to add PSR-4 support in the future, but by default you should use PSR-0 to place your class paths.

Currently Poggit is including no files at all because you have no source folder.

**Comment by thebigsmileXD** [comment]
Thanks for replying to this quite fast, i didn't knew poggit isn't capable of that yet.
I'll reconfigure it based on that.

### (wait.. github tells me a day ago but didn't show the issue..)

**Comment by thebigsmileXD** [comment]
Fixed btw
