### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by AyyItzJ4y** [thebigsmileXD/customui#10]
How do you combine the Custom modal to another modal like a shop

**Comment by TommoVirtualReality** [comment]
That isn't a modal, it's either a simpleform or a custom form.

You create a simple form or custom like this ```$ui = new SimpleForm()```

Or a custom form like ```$ui = new CustomForm()``` - read wiki for detailed explanation. Also recommended to read that before bugging the issue tracker 😉.

**Comment by AyyItzJ4y** [comment]
https://imgur.com/a/tY3BA

**Comment by AyyItzJ4y** [comment]
[download.zip](https://github.com/thebigsmileXD/customui/files/1308111/download.zip)

**Comment by AyyItzJ4y** [comment]
if you know the problen fix it please thanks!

**Comment by thebigsmileXD** [comment]
This is an API, the issue tracker is for API related issues, not for coding help. Read the wiki!
