### ISSUE TITLE
[NOT SPAM] Undefined Offset

### ISSUE THREAD

**Issue by TommoVirtualReality** [thebigsmileXD/customui#11]
Xenial, i know u said not to spam but im not kidding. Im getting this issue. Pls help senpai. @thebigsmileXD 

```17.09 13:03:20 [Server] Server thread/CRITICAL ErrorException: "Undefined offset: 2" (EXCEPTION) in "customuitest/src/xenialdan/customui/API" at line 70```
```17.09 13:03:20 [Server] Server thread/CRITICAL Unhandled exception executing command 'cui testmodal' in cui: Undefined offset: 2```

**Comment by thebigsmileXD** [comment]
Spam. Duplicating issues to be noticed. Banned
