### ISSUE TITLE
Issu with images or url

### ISSUE THREAD

**Issue by armagadon159753** [thebigsmileXD/customui#12]
![screenshot_2017-09-23-17-57-05](https://user-images.githubusercontent.com/25569806/30775009-bb9461ac-a08b-11e7-82be-5278e6412b5a.png)

`
public function reloadUIs(){
		/*
		UIAPI::resetUIs($this);
		$ui = new SimpleForm('Henoria', '');
		$ui->addButton(new Button('Button'));
		$button2 = new Button('ImageButton');
		$button2->addImage(Button::IMAGE_TYPE_URL, 'https://www.google.fr/imgres?imgurl=https%3A%2F%2Fwww.hardcraft.fr%2Fuploads%2F8e39e17c6c5a5be0f65d4874ce671e5c.png&imgrefurl=http%3A%2F%2Fhardcraft.buycraft.net%2F&docid=6k1cavGZ7LeqCM&tbnid=qszSU6xaBvnTPM%3A&vet=10ahUKEwj3jd7s0bvWAhWBPBoKHbZPA5IQMwgxKAIwAg..i&w=190&h=165&bih=559&biw=360&q=vip%2B&ved=0ahUKEwj3jd7s0bvWAhWBPBoKHbZPA5IQMwgxKAIwAg&iact=mrc&uact=8');
		$ui->addButton($button2);
		self::$uis['simpleUI'] = UIAPI::addUI($this, $ui);
		*/
		$ui = new SimpleForm('Mini-Games', 'Selection des Mini-Games');
		$button = new Button('GUN-GAME'); $button->addImage(Button::IMAGE_TYPE_PATH, "https://www.google.fr/search?biw=360&bih=336&tbs=ic%3Atrans&tbm=isch&sa=1&ei=4IXGWZntCYjcaIHaoogG&q=gun+game+minecraft&oq=gun+game+minectaft&gs_l=mobile-gws-img.1.0.30i10k1.6030.9004.0.9976.11.10.0.0.0.0.748.2039.2j4j1j1j6-1.9.0....0...1.1j4.64.mobile-gws-img..2.4.1293...0j0i30k1.113.mo1bFnUTMG4#");
		$ui->addButton($button);
		$button = new Button('UHC-RUN'); $button->addImage(Button::IMAGE_TYPE_URL, "https://www.google.fr/imgres?imgurl=http%3A%2F%2Fstatic.mcgamer.net%2Fi%2Flogo%2Fuhc.png&imgrefurl=http%3A%2F%2Fnoxcrew.com%2Fthreads%2Fnoxsquad-game-night-minecraft-uhc-037-18-06-16.3027%2F&docid=kKzQ0T3PJhpaqM&tbnid=OGzJEjDzVpKWHM%3A&vet=10ahUKEwiy_63317vWAhVD2RoKHUnoAX8QMwgxKAIwAg..i&w=576&h=574&bih=559&biw=360&q=uhc-run%20minecraft&ved=0ahUKEwiy_63317vWAhVD2RoKHUnoAX8QMwgxKAIwAg&iact=mrc&uact=8");
		$ui->addButton($button);
		$button = new Button('1VS1'); $button->addImage(Button::IMAGE_TYPE_PATH, "https://www.google.fr/imgres?imgurl=https%3A%2F%2Fproxy.spigotmc.org%2F6a01b1d78b1de71d21256eecbdd5b646e1e623af%3Furl%3Dhttp%253A%252F%252Fi.imgur.com%252FNUbKBFl.png&imgrefurl=https%3A%2F%2Fwww.spigotmc.org%2Fresources%2Ftrainingpvp-a-duel-plugin-1v1-2v2-party-vs-party-party-ffa-and-party-battle-new-builduhc.5172%2F&docid=UDkUTRae0yuAwM&tbnid=TAS87w3TRSW5HM%3A&vet=10ahUKEwjHp6Ch2LvWAhWCWRoKHce0CaQQMwg3KAcwBw..i&w=636&h=277&bih=559&biw=360&q=1vs1%20minecraft&ved=0ahUKEwjHp6Ch2LvWAhWCWRoKHce0CaQQMwg3KAcwBw&iact=mrc&uact=8");
		$ui->addButton($button);
		self::$uis['simpleUI'] = UIAPI::addUI($this, $ui);
	}
`

**Comment by thebigsmileXD** [comment]
Thanks, appreciating the debug :D not many people detail the debug anymore

Have you tried the direct link? http://static.mcgamer.net/i/logo/uhc.png

**Comment by armagadon159753** [comment]
I will test that but have fount other issu

`2017-09-24 [20:01:49] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'customuitest v1': Call to undefined method xenialdan\customuitest\EventListener::handleServerSettingsRequestPacket() on xenialdan\customuitest\EventListener
2017-09-24 [20:01:49] [Server thread/CRITICAL]: Error: "Call to undefined method xenialdan\customuitest\EventListener::handleServerSettingsRequestPacket()" (EXCEPTION) in "customui1/src/xenialdan/customuitest/EventListener" at line 39
`
Line 39:

`$this->handleServerSettingsRequestPacket($packet, $player);`

**Comment by thebigsmileXD** [comment]
"customui1"

**Comment by armagadon159753** [comment]
Yes i have modified the exemple plugin 
-dell subcommand 
- add onCommand  on Loader.php

**Comment by thebigsmileXD** [comment]
Have you fully read the wiki?
