### ISSUE TITLE
ERROR ON DISPLAY TOTAL PLAYERS IN FORM

### ISSUE THREAD

**Issue by FreakingDev** [thebigsmileXD/customui#15]
I got this error. Can you give me some tips to display it in button

Call to a member function getPlayers() on null" (EXCEPTION) in "myzip://PHCUI.zip#PHCUI/src/xenialdan/customuitest/Loader" at line 60

This is my code

                $level = $this->getServer()->getLevelByName("Pvp");
		$pcount = count($level->getPlayers());
		
		$ui = new SimpleForm('PVP', '$pcount playing');
		$ui->addButton(new Button('1 VS 1'));
		$ui->addButton(new Button('TEAM PVP'));
		self::$uis['pvpUI'] = UIAPI::addUI($this, $ui);

**Comment by Khaled098YT** [comment]
lol just load the world, if you are in the PluginBase do 
$this->getServer()->loadLevel("Pvp");

**Comment by KairusDarkSeeker** [comment]
Close this issue

**Comment by FreakingDev** [comment]
@Khaled098YT  im talking in how to display total players in a button not in loading a world
