### ISSUE TITLE
PLEASE ANSWER IT

### ISSUE THREAD

**Issue by FreakingDev** [thebigsmileXD/customui#18]
How can i add total players in button

![minecraft 04_10_2017 5_27_44 pm](https://user-images.githubusercontent.com/31030234/31168934-b06d8a46-a929-11e7-9721-860cedb93025.png)

**Comment by KairusDarkSeeker** [comment]
Just stfu and close this issue

**Comment by armagadon159753** [comment]
@KairusDarkSeeker you can ask other dev on poggit

**Comment by thebigsmileXD** [comment]
Ban for spamming duplicates
