### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DroidPlaysM** [thebigsmileXD/customui#2]
How would i make the button run a command like let say for the TestSimpleSubCommand i want the button to run command /spawn how would i do that. I'm still learning plugin development.

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/customui/commit/f1525defecbc443902bcc09a81f6b52b2278d7d8#diff-1 it should all be understandable by this commit.

**Comment by thebigsmileXD** [comment]
```$event->getData();

**Comment by thebigsmileXD** [comment]
```php
$data = $event->getData();

$buttondata = $data[index /* most likely 0 if you only have a button*/];

//do whatever you want here with your data
```

**Comment by TommoVirtualReality** [comment]
What would $event be? I'm new to developing so could you add basic command handling in the example plugin? @thebigsmileXD

**Comment by TommoVirtualReality** [comment]
How would you use this though? @jasonwynn10 . 

Should I declare a function for this separately? 😞

**Comment by thebigsmileXD** [comment]
Lock to prevent useless questions. Learn PHP before your code.
https://github.com/thebigsmileXD/customui/blob/master/examples/customuitest/src/xenialdan/customuitest/EventListener.php
If you'd open your eyes you'd see a folder named EXAMPLE. Guess what its for.

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/customui/wiki/
