### ISSUE TITLE
Example plugin request

### ISSUE THREAD

**Issue by MSG100TC** [thebigsmileXD/customui#22]
Hi thebigsmileXD,

The UI plugin is really cool and well made. But after reading the wiki for it, I still can't quite understand.
May I have an example gui of how it works? (Permissons, pictures, image, description...)

For ex.
How do I make a shop gui? Its  like running the command with /shop, and the new window pops up with all the variations of items players can buy. (Similar as the shop in the wiki page)

**Comment by thebigsmileXD** [comment]
- Read the wiki
- Read closed issues, for example #21 
- Read the example plugin's source.
