### ISSUE TITLE
can you make a video or a step to step instructions on how to set it up?

### ISSUE THREAD

**Issue by MegaGastPvP** [thebigsmileXD/customui#23]
can you make a video or a step to step instructions on how to set it up?
 
it would help a lot of people if you did

**Comment by VoxCeleste** [comment]
step by step is on wiki already

**Comment by AyyItzJ4y** [comment]
Try learning for you self now please close this

**Comment by armagadon159753** [comment]
The wiki explail all 
I m not english but i understand

**Comment by thebigsmileXD** [comment]
//Removed spam comments

I theoretically could, but i have no time for that.

Read the WIKI.
