### ISSUE TITLE
Syntax error: value , object or array expected....

### ISSUE THREAD

**Issue by armagadon159753** [thebigsmileXD/customui#26]
When i put `»` or `«` on textarea UI say that

line: `$button = new Button("» Lobby «\n" . $playersOnline . "/" . $maxOnline);`

![screenshot_2017-10-17-22-11-14](https://user-images.githubusercontent.com/25569806/31687289-1e4e1760-b389-11e7-898a-bba541e6a113.png)

**Comment by thebigsmileXD** [comment]
Client issue. Encode it before sending for example. It's a special symbol

**Comment by armagadon159753** [comment]
Okay @thebigsmileXD 
I imagine that it is the same problem for this symbol §

just a question out of curiosity:
it is possible to check the StepSlider or other elecments?

**Comment by thebigsmileXD** [comment]
You do not use §, you use TextFormat.

https://github.com/thebigsmileXD/customui/wiki/5-Response-handling Read the Wiki. You get the value of any element
