### ISSUE TITLE
other ui's dispatching comnands from different UI

### ISSUE THREAD

**Issue by karanpatel567** [thebigsmileXD/customui#27]
hey do you know why it does this I checked through everything can't seem to solve it.

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/customui#i-will-drop-support-and-development-of-customui-api-use-httpstcodzregfzerg-by-dktapps-instead---and-blame-him-on-issues

**Comment by thebigsmileXD** [comment]
This bug is the exact reason i dropped the support
