### ISSUE TITLE
How to make commands occur because example didnt have that. 

### ISSUE THREAD

**Issue by TommoVirtualReality** [thebigsmileXD/customui#4]
@thebigsmileXD The example folder or testsimple doesn't show at all how you'd set a button doing a command. I'm new like I said (don't insult me). How would you have for example button 1 doing command `hello` and button doing command `bye`.

**Comment by thebigsmileXD** [comment]
Create another issue just to spam and you get banned.

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/customui/issues/2

Use the fucking search.
