### ISSUE TITLE
Everyone read this before asking stupid stuff

### ISSUE THREAD

**Issue by TommoVirtualReality** [thebigsmileXD/customui#5]
Umm Jason or @thebigsmileXD .. I still don't understand

What is `$ev` in issue #2 

Please help. I'm noob.

**Comment by jasonwynn10** [comment]
$ev is the class form the link I posted

**Comment by thebigsmileXD** [comment]
Please read the source before asking

**Comment by TommoVirtualReality** [comment]
So how would I declare it? Like this?

```public function getClientData(UIDataReceiveEvent $ev)
$formdata = $ev->getData();
if($formdata == 0){
// Command to run here
Return true;
}
}``` ?

**Comment by thebigsmileXD** [comment]
![image](https://user-images.githubusercontent.com/8733998/30231278-7a9cbbec-94ea-11e7-923d-2c42f6b62420.png)
![image](https://user-images.githubusercontent.com/8733998/30231296-8b412294-94ea-11e7-88e9-8b06c390651d.png)

**Comment by TommoVirtualReality** [comment]
Wouldn't it be easier for us if you showed us how to do this in the example plugin? For example have a button run the command `gamemode s`.

**Comment by thebigsmileXD** [comment]
It basically IS in the example plugin.

**Comment by thebigsmileXD** [comment]
Actually its not in the example because the ID is not unique. Windows with same titles create errors

**Comment by TommoVirtualReality** [comment]
Well example plugin doesn't really tell me how I could have button plugin doing command `gamemode c`.. or I'm too dumb to understand it - either way, would be better if the example plugin had a Simple form with a button doing a certain command.

**Comment by thebigsmileXD** [comment]
Enjoy the ban

**Comment by thebigsmileXD** [comment]
https://github.com/thebigsmileXD/customui/wiki I hope this can answer all your questions, especially https://github.com/thebigsmileXD/customui/wiki/5-Response-handling#i-want-it-simple-dumbledore
